name: dnn_setup
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dnn_core:
    path: ../dnn_core/
  dnn_shared:
    path: ../dnn_shared/
  dnn_authentication:
    path: ../dnn_authentication/
  dnn_dependencies:
    path: ../dnn_dependencies/
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
