name: dnn_start_appointment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1

  dnn_shared:
    path: ../dnn_shared/
  dnn_core:
    path: ../dnn_core/
  dnn_pages:
    path: ../dnn_pages/
  dnn_campaign:
    path: ../dnn_campaign/
  dnn_dependencies:
    path: ../dnn_dependencies/
  dnn_streamming:
    path: ../dnn_streamming/
  dnn_invoices:
    path: ../dnn_invoices/
  dnn_app:
    path: ../dnn_app/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
