// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqngzvTrR9ORHusAJzwZFoWD291AQvuhg',
    appId: '1:239174645502:web:a3cf745760db2edde097af',
    messagingSenderId: '239174645502',
    projectId: 'dnnapp-516ac',
    authDomain: 'dnnapp-516ac.firebaseapp.com',
    storageBucket: 'dnnapp-516ac.appspot.com',
    measurementId: 'G-E70LSVK52J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt9x2Z7Blu-7vLio078v4X_VsIB545ctw',
    appId: '1:239174645502:android:a31e2b207d159166e097af',
    messagingSenderId: '239174645502',
    projectId: 'dnnapp-516ac',
    storageBucket: 'dnnapp-516ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD2GOGb6rPfDCGUItrIncIMPjHTLvKwxM',
    appId: '1:239174645502:ios:57fac618d8f13bd7e097af',
    messagingSenderId: '239174645502',
    projectId: 'dnnapp-516ac',
    storageBucket: 'dnnapp-516ac.appspot.com',
    iosClientId: '239174645502-d8cnasnsc77h682quc7t3hn6prgkd93c.apps.googleusercontent.com',
    iosBundleId: 'br.com.dnn.app',
  );
}
