name: dnn_shared
description: Projeto de compartilhamento de elementos gráficos.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_credit_card: ^3.0.7
  webview_flutter: ^4.4.2
  flutter_widget_from_html: ^0.10.6
  clipboard: ^0.1.3
  flutter_inappwebview: ^5.8.0
  image_picker: ^1.0.4
  flutter_share: ^2.0.0
  cached_network_image: 3.3.0
  uuid: ^3.0.7
  url_launcher: ^6.2.1
  font_awesome_flutter: ^10.6.0
  auto_size_text: ^3.0.0
  sliver_app_bar_builder: ^1.1.0
  xml: ^6.4.2
  awesome_bottom_bar: ^1.2.4
  flutter_pdfview: ^1.3.2
  upgrader: ^8.2.0
  transparent_image: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  table_calendar: ^3.0.9
  maps_launcher: ^2.2.0
  material_design_icons_flutter: ^7.0.7296
  flutter_keyboard_visibility: ^5.4.1

  dnn_core:
    path: ../dnn_core/
  dnn_dependencies:
    path: ../dnn_dependencies/
  dnn_helpers:
    path: ../dnn_helpers/
  dnn_pages:
    path: ../dnn_pages/
  dnn_app:
    path: ../dnn_app/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/dnn_horizontal/
    - assets/dnn_icons/
    - assets/dnn_vertical/
