name: dnn_shopping_cart
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dnn_core:
    path: ../dnn_core/
  dnn_dependencies:
    path: ../dnn_dependencies/
  dnn_shared:
    path: ../dnn_shared/
  dnn_campaign:
    path: ../dnn_campaign/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
