name: dnn_dependencies
description: Package responsável por fazer a gestão das dependências externas utilizadas
version: 0.0.1
homepage: DNN
publish_to: "none"

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter_localizations:
    #sdk: flutter
    #intl: any

  flutter_flavor: ^3.1.3
  signalr_core: ^1.1.1
  brasil_fields: ^1.14.0
  cupertino_icons: ^1.0.6
  dart_ipify: ^1.1.1
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  firebase_core_web: ^2.8.1
  firebase_analytics: ^10.7.0
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4
  firebase_crashlytics: ^3.4.4
  gtm: ^0.1.2
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  intl: ^0.19.0
  local_auth: ^2.1.7
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  encrypt: ^5.0.3
  mask_text_input_formatter: ^2.5.0
  dropdown_search: ^5.0.6
  qr_mobile_vision: ^4.1.3
  qr_flutter: ^4.1.0
  connectivity_plus: ^3.0.6
  get: ^4.6.6
  logger: ^2.0.2+1
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.9
  bot_toast: ^4.1.3
  text_helpers: ^1.0.2+1
  get_storage: ^2.1.1
  flutter_credit_card: ^3.0.7
  otp_text_field: ^1.1.3
  cached_network_image: 3.3.0
  another_flushbar: ^1.12.30
  flutter_screenutil: ^5.9.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0
  flutter_secure_storage: ^9.0.0
  diacritic: ^0.1.4
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.2+3
  flutter_widget_from_html: ^0.10.6
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
